defaults:
  - agents: bc_agent
#  - override hydra/launcher: submitit_slurm

agent_name: bc
log_dir: logs/aligning/

train_data_path: environments/dataset/data/aligning/train_files.pkl
eval_data_path: environments/dataset/data/aligning/eval_files.pkl

hydra:
  run:
    dir: ${log_dir}/runs/${agent_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${log_dir}/sweeps/${agent_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.override_dirname}

# insert wandb here
wandb:
  entity: atalaydonat
  project: d3il

group: aligning_${agent_name}

seed: 42

# Network
hidden_dim: 128
num_hidden_layers: 6

# transformer
n_layer: 4
n_head: 4
n_embd: 72

# Training
train_batch_size: 1024
val_batch_size: 1024
num_workers: 4
device: 'cuda'
epoch: 500
eval_every_n_epochs: 50
scale_data: True

# Environment
obs_dim: 20
action_dim: 3
max_len_data: 512
window_size: 1

# Dataset
trainset:
  _target_: environments.dataset.aligning_dataset.Aligning_Dataset
  data_directory: ${train_data_path}
  obs_dim: ${obs_dim}
  action_dim: ${action_dim}
  max_len_data: ${max_len_data}
  window_size: ${window_size}

valset:
  _target_: environments.dataset.aligning_dataset.Aligning_Dataset
  data_directory: ${eval_data_path}
  obs_dim: ${obs_dim}
  action_dim: ${action_dim}
  max_len_data: ${max_len_data}
  window_size: ${window_size}

# Simulation
simulation:
  _target_: simulation.aligning_sim.Aligning_Sim
  seed: ${seed}
  device: ${device}
  render: False
  n_cores: 30
  n_contexts: 60
  n_trajectories_per_context: 8