defaults:
  - agents: bc_agent

agent_name: bc
log_dir: logs/stacking/


train_data_path: environments/dataset/data/stacking/train_files.pkl
eval_data_path: environments/dataset/data/stacking/eval_files.pkl

# insert wandb here
wandb:
  entity: atalaydonat
  project: d3il

group: stacking_${agent_name}

hydra:
  run:
    dir: ${log_dir}/runs/${agent_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${log_dir}/sweeps/${agent_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.override_dirname}


seed: 42

# Network
hidden_dim: 256
num_hidden_layers: 8

# transformer
n_layer: 6
n_head: 6
n_embd: 120

# Training
train_batch_size: 1024
val_batch_size: 1024
num_workers: 4
device: 'cuda'
epoch: 200
eval_every_n_epochs: 10
scale_data: True

# Environment
obs_dim: 20 # robot_feature + obj_feature * num_obj
action_dim: 8
max_len_data: 1000
window_size: 5

shape_meta: &shape_meta
  robot_feature:
    shape: [8] # robot_des_j_pos, robot_gripper
  obj_feature:
    shape: [4] # box_pos, box_euler_angle_z

# Dataset
trainset:
  _target_: environments.dataset.stacking_dataset.Stacking_Dataset
  data_directory: ${train_data_path}
  obs_dim: ${obs_dim}
  action_dim: ${action_dim}
  max_len_data: ${max_len_data}
  window_size: ${window_size}

valset:
  _target_: environments.dataset.stacking_dataset.Stacking_Dataset
  data_directory: ${eval_data_path}
  obs_dim: ${obs_dim}
  action_dim: ${action_dim}
  max_len_data: ${max_len_data}
  window_size: ${window_size}

# Simulation
simulation:
  _target_: simulation.stacking_sim.Stacking_Sim
  seed: ${seed}
  device: ${device}
  render: True
  n_cores: 1
  n_contexts: 5
  n_trajectories_per_context: 1
  max_steps_per_episode: 1000