defaults:
  - agents: bc_vision_agent
  - override hydra/launcher: submitit_slurm

agent_name: bc_vision
log_dir: logs/stacking/

#data_directory: environments/dataset/data/stacking/joint_data

train_data_path: environments/dataset/data/stacking/vision_train_files.pkl
eval_data_path: environments/dataset/data/stacking/vision_eval_files.pkl

# insert wandb here
wandb:
  entity: ???
  project: ???

group: stacking_${agent_name}

hydra:
  run:
    dir: ${log_dir}/runs/${agent_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${log_dir}/sweeps/${agent_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.override_dirname}

  launcher:
    timeout_min: 1800
    name: stacking #${hydra.job.name}
    partition: accelerated
#    gpus_per_node: 4
    additional_parameters: {"ntasks":1, "gres":gpu:4, "cpus-per-task":152}


seed: 42

# Network
hidden_dim: 128
num_hidden_layers: 4

# transformer
n_layer: 4
n_head: 4
n_embd: 72

# Training
train_batch_size: 512
val_batch_size: 512
num_workers: 2
device: 'cuda'
epoch: 200
eval_every_n_epochs: 20
scale_data: True

# Environment
obs_dim: 8 # robot_feature + obj_feature * num_obj
action_dim: 8
max_len_data: 1000
window_size: 5

# Dataset
trainset:
  _target_: environments.dataset.stacking_dataset.Stacking_Img_Dataset
  data_directory: ${train_data_path}
  obs_dim: ${obs_dim}
  action_dim: ${action_dim}
  max_len_data: ${max_len_data}
  window_size: ${window_size}

valset:
  _target_: environments.dataset.stacking_dataset.Stacking_Img_Dataset
  data_directory: ${eval_data_path}
  obs_dim: ${obs_dim}
  action_dim: ${action_dim}
  max_len_data: ${max_len_data}
  window_size: ${window_size}

# sim during training
train_simulation:
  _target_: simulation.stacking_vision_sim.Stacking_Sim
  seed: ${seed}
  device: ${device}
  render: False
  n_cores: 5
  n_contexts: 30
  n_trajectories_per_context: 1
  max_steps_per_episode: 1200
  if_vision: True

# Simulation
simulation:
  _target_: simulation.stacking_vision_sim.Stacking_Sim
  seed: ${seed}
  device: ${device}
  render: False
  n_cores: 5
  n_contexts: 60
  n_trajectories_per_context: 18
  max_steps_per_episode: 1200
  if_vision: True